#! /bin/bash
# tar-1.13 for pkgtool

if [ "$1" != "" ]; then
        export MJ="-j$1"
else
        export MJ=""
fi

export CC="${MLFS_TARGET}-gcc"
export CXX="${MLFS_TARGET}-g++"
export AR="${MLFS_TARGET}-ar"
export AS="${MLFS_TARGET}-as"
export RANLIB="${MLFS_TARGET}-ranlib"
export LD="${MLFS_TARGET}-ld"
export STRIP="${MLFS_TARGET}-strip"

cd .. && tar xf tar-1.13.tar.gz && cd tar-1.13 
echo "[ TC - pkgtool ] Configure tar-1.13 source ..." 
cp -v ../files/config.sub-musl config.sub
cp -v ../files/config.guess-musl config.guess

./configure --build=${MLFS_HOST} \
            --host=${MLFS_TARGET} \
            --prefix=/tools \
            --disable-nls &&
read -p "[ TC - pkgtool ] Compile tar-1.13? " && make $MJ &&
read -p "[ TC - pkgtool ] Install tar-1.13? " && install -m0755 src/tar /tools/bin/tar-1.13 &&

read -p "[ TC - pkgtool ] Install? &&
cd ../pkgtool/scripts &&
for prog in installpkg makepkg removepkg; do
	install -m755 $prog /tools/bin/
done


