#! /bin/bash

# syntax:
# enter package build 
# buildpkg <packagename-version>

export BUILDDIR=/sources/BUILD
export PKGSDIR=/sources/PKGS

#mkdir -pv $BUILDDIR/$1/install
#touch $BUILDDIR/$1/install/slack-desc

/sbin/makepkg -l y -c n $PKGSDIR/$1-x86_64-musl-mlfs.txz
