#! /bin/bash

# Musl Libc 
# Source: https://www.musl-libc.org/releases/musl-1.2.1.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="musl"  &&
export   VER="1.2.1" &&
export  MJOB="-j2"   &&

patch -Np0 -i ../patches/musl-1.2.1-void/mo_lookup.patch            &&
case $(uname -m) in
   i686) patch -Np1 -i ../patches/musl-mlfs/i686-fix-rounding.patch ;;
esac &&
patch -Np1 -i ../patches/musl-adelie/3001-make-real-lastlog-h.patch &&
patch -Np1 -i ../patches/musl-adelie/amalgamation.patch             &&
patch -Np1 -i ../patches/musl-adelie/fgetspent_r.patch              &&
patch -Np1 -i ../patches/musl-adelie/handle-aux-at_base.patch       &&
patch -Np1 -i ../patches/musl-adelie/threads_minus_2.patch          &&
patch -Np1 -i ../patches/musl-adelie/CVE-2020-28928.patch &&

case $(uname -m) in
     i686) export CARCH="i386"    ;;
   x86_64) export CARCH="x86_64"  ;;
     arm*) export CARCH="arm"     ;;
  aarch64) export CARCH="aarch64" ;;
esac &&

LDFLAGS="$LDFLAGS -Wl,-soname,libc.musl-${CARCH}.so.1" \
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --disable-gcc-wrapper &&
time { make ${MJOB} ; }  &&
make DESTDIR=${BUILD} install &&

/tools/bin/$(uname -m)-mlfs-*-gcc -fpie -c \
../files/musl-alpine/__stack_chk_fail_local.c -o __stack_chk_fail_local.o &&
/tools/bin/$(uname -m)-mlfs-*-gcc-ar r \
libssp_nonshared.a __stack_chk_fail_local.o                               &&                                            &&
install -v -D -m755 libssp_nonshared.a ${BUILD}/usr/lib/                  &&

mkdir -pv ${BUILD}/bin &&
ln -sv ../usr/lib/libc.so ${BUILD}/bin/ldd &&

mkdir -pv ${BUILD}/etc/ &&
printf "/lib \n"            >> ${BUILD}/etc/ld-musl-$CARCH.path &&
printf "/usr/local/lib \n"  >> ${BUILD}/etc/ld-musl-$CARCH.path &&
printf "/usr/lib \n"        >> ${BUILD}/etc/ld-musl-$CARCH.path &&

case $(uname -m) in
     i686) ln -sv ../usr/lib/libc.so  ${BUILD}/lib/ld-musl-i686.so.1 ;;
esac &&
unset CARCH &&
mkdir -pv ${BUILD}/usr/bin &&
install -v -D -m755 ../files/musl-adelie/ldconfig ${BUILD}/usr/bin/ &&

rm -v ${BUILD}/usr/include/utmp.h   &&
rm -v ${BUILD}/usr/include/utmpx.h  &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

