#! /bin/bash

# Timezone Data and utilities
# Source: https://www.iana.org/time-zones/repository/releases/tzdata2020a.tar.gz
# Source: https://www.iana.org/time-zones/repository/releases/tzcode2020a.tar.gz
# Source: https://dev.alpinelinux.org/archive/posixtz/posixtz-0.5.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="tzdb"  &&
export   VER="2020a" &&
export  MJOB="-j2"   &&

export timezones="africa antarctica asia australasia europe northamerica \
                  southamerica pacificnew etcetera backward systemv factory"
mkdir tzdb && cd tzdb &&
tar xf ../tzdata2020a.tar.gz &&
tar xf ../tzcode2020a.tar.gz &&
tar xf ../posixtz-0.5.tar.xz &&

patch -Np1 -i ../patches/posixtz-adelie/0001-posixtz-fix-up-lseek.patch &&

make CFLAGS="$CFLAGS -DHAVE_STDINT_H=1" TZDIR="/usr/share/zoneinfo" ${MJOB} &&
make -C posixtz-0.5 posixtz ${MJOB} &&

mkdir -pv ${BUILD}/usr/share/zoneinfo/right &&
mkdir -pv ${BUILD}/usr/sbin                 &&
mkdir -pv ${BUILD}/usr/share/man/man8       &&
./zic -y ./yearistype -d ${BUILD}/usr/share/zoneinfo ${timezones}
./zic -y ./yearistype -d ${BUILD}/usr/share/zoneinfo/right -L leapseconds ${timezones}
./zic -y ./yearistype -d ${BUILD}/usr/share/zoneinfo -p America/New_York
install -m444 -t ${BUILD}/usr/share/zoneinfo iso3166.tab zone1970.tab zone.tab
install -m755 zic zdump ${BUILD}/usr/sbin
install -m644 zic.8 zdump.8 ${BUILD}/usr/share/man/man8
install -v -Dm755 posixtz-0.5/posixtz ${BUILD}/usr/bin/posixtz
unset timezones

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

