#! /bin/bash

# Argp-Standalone
# Source: http://www.lysator.liu.se/~nisse/misc/argp-standalone-1.3.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="argp-standalone"  &&
export   VER="1.3"              &&
export  MJOB="-j2"              &&

patch -Np0 -i ../patches/argp-standalone-void/fix-no_use_inline.patch       &&
patch -Np1 -i ../patches/argp-standalone-adelie/001-throw-in-funcdef.patch  &&
patch -Np1 -i ../patches/argp-standalone-adelie/gnu89-inline.patch          &&

CFLAGS=" -fPIC" ./configure --prefix=/usr     \
                            --disable-static  \
                            --sysconfdir=/etc \
                            --localstatedir=/var ${BTRUPLE} &&
read -p "Compile?" && make ${MJOB} &&

mkdir -pv ${BUILD}/usr/{lib,include}                 &&
install -v -D -m644  libargp.a ${BUILD}/usr/lib/     &&
install -v -D -m644  argp.h    ${BUILD}/usr/include/ &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

