#! /bin/bash

# m4
# Source: http://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="m4" &&
export   VER="1.4.18" &&
export  MJOB="-j2" &&

patch -Np1 -i ../patches/m4-adelie/disable-mbrtowc-test.patch                      &&
patch -Np1 -i ../patches/m4-adelie/gnulib-tests-dont-require-gpg-passphrase.patch  &&
patch -Np1 -i ../patches/m4-adelie/localename-test-fix.patch                       &&

./configure --prefix=/usr $BTRUPLE &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

