#! /bin/bash

# Shadow
# Source: https://github.com/shadow-maint/shadow/releases/download/4.8.1/shadow-4.8.1.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="shadow" &&
export   VER="4.8.1"  &&
export  MJOB="-j2"    &&

sed -i 's/groups$(EXEEXT) //' src/Makefile.in                      &&
find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;  &&
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;  &&
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;  &&
sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs            &&
sed -i 's/1000/999/' etc/useradd                                   &&
touch /usr/bin/passwd &&
LIBS="-lutmps -lskarnet" \
./configure --with-group-name-max-length=32 \
            --sysconfdir=/etc \
            --enable-utmpx $BTRUPLE &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&
mv -v ${BUILD}/usr/bin/passwd ${BUILD}/bin &&
sed -i 's/yes/no/' ${BUILD}/etc/default/useradd &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
printf "echo 'Enabling shadowed passwords...' \n" >> ${BUILD}/install/doinst.sh &&
printf "pwconv && grpconv \n"                     >> ${BUILD}/install/doinst.sh &&
printf "echo 'Set system root password:' \n"      >> ${BUILD}/install/doinst.sh &&
printf "passwd root \n"                           >> ${BUILD}/install/doinst.sh &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

