#! /bin/bash

# GCC
# Source:  http://ftp.gnu.org/gnu/gcc/gcc-10.2.0/gcc-10.2.0.tar.xz
# Source: http://isl.gforge.inria.fr/isl-0.19.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="gcc"    &&
export   VER="10.2.0" &&
export  MJOB="-j2"    &&

case $(uname -m) in
  x86_64) export TRUPLE="x86_64-linux-musl"
          export EXTRA_CONFIG=" --with-arch=x86-64"
          ;;
  i686)   export TRUPLE="i686-linux-musl"
          export EXTRA_CONFIG=" --with-arch=pentium3 --with-tune=pentium-m"
          ;;
  armv7l) export TRUPLE="armv7l-linux-musleabihf"
          export EXTRA_CONFIG=" --with-arch=armv7-a --with-tune=generic-armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-abi=aapcs-linux --with-mode=thumb"
          ;;
  armv6l) export TRUPLE="armv6l-linux-musleabihf"
          export EXTRA_CONFIG=" --with-arch=armv6zk --with-tune=arm1176jzf-s --with-fpu=vfp --with-float=hard --with-abi=aapcs-linux"
          ;;
  aarch64) export TRUPLE="aarch64-linux-musleabihf"
           export EXTRA_CONFIG=" --with-arch=armv8-a --with-abi=lp64 --enable-fix-cortex-a53-835769 --enable-fix-cortex-a53-843419"
           sed -i '/m64=/s/lib64/lib/' gcc/config/aarch64/t-aarch64-linux
          ;;
esac &&

case $(uname -m) in
     arm*) export LIBITM=false ;;
esac &&

tar -xf ../isl-0.19.tar.xz &&
mv -v isl-0.19 isl         &&

for p in 0001-posix_memalign.patch \
         0002-gcc-poison-system-directories.patch \
         0003-Turn-on-Wl-z-relro-z-now-by-default.patch \
         0004-Turn-on-D_FORTIFY_SOURCE-2-by-default-for-C-C-ObjC-O.patch \
         0005-On-linux-targets-pass-as-needed-by-default-to-the-li.patch \
         0006-Enable-Wformat-and-Wformat-security-by-default.patch \
         0007-Enable-Wtrampolines-by-default.patch \
         0008-Disable-ssp-on-nostdlib-nodefaultlibs-and-ffreestand.patch \
         0009-Ensure-that-msgfmt-doesn-t-encounter-problems-during.patch \
         0010-Don-t-declare-asprintf-if-defined-as-a-macro.patch \
         0011-libiberty-copy-PIC-objects-during-build-process.patch \
         0012-libitm-disable-FORTIFY.patch 0013-libgcc_s.patch \
         0014-nopie.patch 0015-libffi-use-__linux__-instead-of-__gnu_linux__-for-mu.patch \
         0016-dlang-update-zlib-binding.patch \
         0017-dlang-fix-fcntl-on-mips-add-libucontext-dep.patch \
         0018-ada-fix-shared-linking.patch \
         0019-build-fix-CXXFLAGS_FOR_BUILD-passing.patch \
         0020-libstdc-futex-add-time64-compatibility.patch \
         0021-add-fortify-headers-paths.patch \
         0022-Alpine-musl-package-provides-libssp_nonshared.a.-We-.patch \
         0023-DP-Use-push-state-pop-state-for-gold-as-well-when-li.patch \
         0024-Pure-64-bit-MIPS.patch \
         0025-use-pure-64-bit-configuration-where-appropriate.patch \
         0026-always-build-libgcc_eh.a.patch \
         0027-ada-libgnarl-compatibility-for-musl.patch \
         0028-ada-musl-support-fixes.patch; do
    patch -Np1 -i ../patches/gcc-10.2.0-alpine/$p
done &&
patch -Np0 -i ../patches/gcc-9.1.0-void/fix-musl-execinfo.patch &&
case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
  ;;
  aarch64)
    sed -e '/mabi.lp64=/s/lib64/lib/' \
        -i.orig gcc/config/aarch64/t-aarch64-linux
  ;;
esac &&
sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" {gcc,libiberty}/configure
mkdir -v build && cd build
SED=sed  libat_cv_have_ifunc=no       \
../configure --prefix=/usr            \
             --build="${TRUPLE}"\
             --with-system-zlib       \
             --with-isl \
             --with-linker-hash-style=gnu \
             --enable-languages=c,c++ \
             --enable-threads=posix \
             --enable-clocale=generic \
             --enable-tls \
             --enable-libstdcxx-time \
             --enable-fully-dynamic-string \
             --enable-default-pie \
             --enable-default-ssp \
             --enable-vtable-verify \
             --enable-linker-build-id \
             --enable-fast-character \
             --disable-libstdcxx-pch \
             --disable-nls \
             --disable-multilib       \
             --disable-bootstrap      \
             --disable-symvers \
             --disable-libsanitizer \
             --disable-target-libiberty \
             --disable-libunwind-exceptions \
             --disable-libssp --disable-libmpx \
             --disable-libmudflap $EXTRA_CONFIG \
             --with-pkgversion="Musl-LFS 8.00" &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&
cc -fpie ../../files/musl/getent.c -o getent    &&
cc -fpie ../../files/musl/getconf.c -o getconf  &&
cc -fpie ../../files/musl/iconv.c -o iconv      &&
install -v -D -m755  getent  ${BUILD}/usr/bin/   &&
install -v -D -m755  getconf ${BUILD}/usr/bin/   &&
install -v -D -m755  iconv   ${BUILD}/usr/bin/   &&
install -v -D -m644  ../../files/musl/getent.1   ${BUILD}/usr/share/man/man1/ &&
install -v -D -m644  ../../files/musl/getconf.1  ${BUILD}/usr/share/man/man1/ &&
mkdir -pv ${BUILD}/lib                  &&
ln -sv ../usr/bin/cpp ${BUILD}/lib/cpp  &&
ln -sv gcc ${BUILD}/usr/bin/cc          &&
install -v -dm755 ${BUILD}/usr/lib/bfd-plugins                          &&
ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/10.2.0/liblto_plugin.so \
        ${BUILD}/usr/lib/bfd-plugins/                                   &&
mkdir -pv ${BUILD}/usr/share/gdb/auto-load/usr/lib                      &&
mv -v ${BUILD}/usr/lib/*gdb.py ${BUILD}/usr/share/gdb/auto-load/usr/lib &&
unset LIBITM &&
case $(uname -m) in
   x86_64* | aarch64* ) mv -v ${BUILD}/usr/lib64/* ${BUILD}/usr/lib/
                        rm -rf ${BUILD}/usr/lib64
                        ln -sv lib ${BUILD}/usr/lib64
                        ;;
esac &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

