#! /bin/bash

# psmisc
# Source: https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.4.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="psmisc" &&
export   VER="23.4"   &&
export  MJOB="-j2"    &&

ac_cv_func_malloc_0_nonnull=yes  \
ac_cv_func_realloc_0_nonnull=yes \
./configure --prefix=/usr        \
            --sysconfdir=/etc     \
            --localstatedir=/var  \
            --disable-selinux     \
            --enable-harden-flags \
            --enable-ipv6 $BTRUPLE &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install      &&
mkdir -pv ${BUILD}/bin             &&
mv -v ${BUILD}/usr/bin/fuser   ${BUILD}/bin &&
mv -v ${BUILD}/usr/bin/killall ${BUILD}/bin &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

