#! /bin/bash

# Iana-etc
# Source:  https://github.com/Mic92/iana-etc/releases/download/20201124/iana-etc-202011124.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="iana-etc"   &&
export   VER="2020.11.24" &&
export  MJOB="-j2"        &&

mkdir -pv ${BUILD}/etc &&
cp -v services protocols ${BUILD}/etc &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

