#! /bin/bash

# Flex
# Source:  https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="flex" &&
export   VER="2.6.4" &&
export  MJOB="-j2" &&

ac_cv_func_malloc_0_nonnull=yes  \
ac_cv_func_realloc_0_nonnull=yes \
HELP2MAN=/tools/bin/true         \

./configure --prefix=/usr \
            --docdir=/usr/share/doc/flex-${VER} $BTRUPLE &&
read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&
ln -sv flex ${BUILD}/usr/bin/lex &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

