#! /bin/bash

# Bash
# Source: http://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="bash" &&
export   VER="5.0" &&
export  MJOB="-j2"  &&

./configure --prefix=/usr                       \
            --docdir=/usr/share/doc/bash-5.0 \
            --without-bash-malloc               \
            --with-installed-readline \
            --with-curses $BTRUPLE &&
read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&
mkdir -pv ${BUILD}/bin        &&
mv -vf ${BUILD}/usr/bin/bash ${BUILD}/bin &&
cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

