#! /bin/bash

# GDBM
# Source:  http://ftp.gnu.org/gnu/gdbm/gdbm-1.18.1.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="gdbm" &&
export   VER="1.18.1"   &&
export  MJOB="-j2"  &&

sed -r -i '/^char.*parseopt_program_(doc|args)/d' src/parseopt.c &&

./configure --prefix=/usr \
            --disable-static \
            --enable-libgdbm-compat $BTRUPLE &&
read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

