#! /bin/bash

# Expat
# Source:  https://prdownloads.sourceforge.net/expat/expat-2.2.10.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="expat" &&
export   VER="2.2.10"   &&
export  MJOB="-j2"   &&

./configure --prefix=/usr \
            --disable-static \
            --docdir=/usr/share/doc/expat-${VER} ${BTRUPLE} &&
read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

