#! /bin/bash

# Intltool
# Source: https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="intltool" &&
export   VER="0.51.0"   &&
export  MJOB="-j2"      &&

sed -i 's:\\\${:\\\$\\{:' intltool-update.in

./configure --prefix=/usr $BTRUPLE &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

