#! /bin/bash

# Autoconf
# Source: http://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="autoconf" &&
export   VER="2.71"     &&
export  MJOB="-j2"      &&

# Starting with 2.70+ version finally supports musl truple
#patch -Np1 -i ../patches/autoconf-2.69-musl.patch &&

./configure --prefix=/usr ${BTRUPLE} &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

