#! /bin/bash

# Xz
# Source: https://tukaani.org/xz/xz-5.2.5.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="xz"    &&
export   VER="5.2.5" &&
export  MJOB="-j2"   &&

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xz-${VER} $BTRUPLE &&
read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&
mkdir -pv ${BUILD}/{bin,lib} &&
mv -v ${BUILD}/usr/bin/{lzma,unlzma,lzcat,xz,unxz,xzcat} ${BUILD}/bin &&
mv -v ${BUILD}/usr/lib/liblzma.so.* ${BUILD}/lib &&
ln -svf ../../lib/liblzma.so.${VER} ${BUILD}/usr/lib/liblzma.so
cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

