#! /bin/bash

# gettext-tiny
# Source: https://distfiles.adelielinux.org/source/gettext-tiny-0.3.1_git20191130.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="gettext-tiny" &&
export   VER="0.3.1"        &&
export  MJOB="-j2"          &&

patch -Np1 -i ../patches/gettext-tiny-adelie/keyword.patch               &&
patch -Np1 -i ../patches/gettext-tiny-adelie/line-length.patch           &&
patch -Np1 -i ../patches/gettext-tiny-adelie/respect-cflags.patch        &&
patch -Np1 -i ../patches/gettext-tiny-adelie/stop-doing-macro-crap.patch &&

read -p "Compile?" && LIBINTL=MUSL prefix=/usr make ${MJOB} &&

make DESTDIR=${BUILD} LIBINTL=MUSL DESTDIR=/ prefix=/usr install &&
cd libtintl && make ${MJOB} clean &&
libtool --tag=CC --mode=compile  gcc -g -O2 -Wall  -c libintl-musl.c &&
libtool --tag=CC --mode=link   gcc -g -O2 -Wall  -o libintl.la &&
## check for linintl.la
# cp -v  libintl.la ${BUILD}/usr/lib/ 

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

