#! /bin/bash

# Libelf
# Source: https://sourceware.org/ftp/elfutils/0.180/elfutils-0.180.tar.bz2
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="libelf" &&
export   VER="0.180"  &&
export  MJOB="-j2"    &&

# Add missing files
cp -vr ../files/elfutils-void/error.h lib/ &&
cp -vr ../files/elfutils-void/error.h src/ &&

patch -Np0 -i ../patches/elfutils-void/fix-aarch64_fregs.patch &&
patch -Np0 -i ../patches/elfutils-void/musl-cdefs.patch        &&
patch -Np0 -i ../patches/elfutils-void/musl-fts-obstack.patch  &&
patch -Np0 -i ../patches/elfutils-void/musl-macros.patch       &&
patch -Np0 -i ../patches/elfutils-void/musl-qsort_r.patch      &&
patch -Np0 -i ../patches/elfutils-void/musl-strerror_r.patch   &&
patch -Np0 -i ../patches/elfutils-void/musl-strndupa.patch     &&
patch -Np0 -i ../patches/elfutils-void/fix-uninitialized.patch &&
patch -Np0 -i ../patches/elfutils-void/musl-asm_ptrace_h.patch &&

autoreconf -ifv &&

CFLAGS="-Wno-error -Wno-error=null-dereference" \
./configure --prefix=/usr --disable-debuginfod \
            --disable-libdebuginfod $BTRUPLE &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} -C libelf install &&
install -vm644 config/libelf.pc /usr/lib/pkgconfig &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

