#! /bin/bash

# Libelf
# Source: https://sourceware.org/ftp/elfutils/0.183/elfutils-0.183.tar.bz2
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="libelf" &&
export   VER="0.183"  &&
export  MJOB="-j2"    &&

# Add missing files
cp -vr ../files/elfutils-void/error.h lib/ &&
cp -vr ../files/elfutils-void/error.h src/ &&

#patch -Np0 -i ../patches/elfutild-void/debuginfod.patch  &&
#patch -Np0 -i ../patches/elfutild-void/fts-obstack.patch &&
#patch -Np0 -i ../patches/elfutild-void/musl-asm_ptrace_h.patch &&
#patch -Np0 -i ../patches/elfutild-void/musl-macros.patch     &&
#patch -Np0 -i ../patches/elfutild-void/musl-qsort_r.patch    &&
#patch -Np0 -i ../patches/elfutild-void/musl-strerror_r.patch &&

autoreconf -ifv &&

CFLAGS="-DFNM_EXTMATCH=0 -Wno-error -Wno-error=null-dereference -Wl,-z,stack-size=2097152" \
./configure --prefix=/usr --disable-debuginfod \
            --disable-libdebuginfod $BTRUPLE &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} -C libelf install &&
install -vm644 config/libelf.pc /usr/lib/pkgconfig &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

