#! /bin/bash

# LibreSSL
# Source:  http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.0.0.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="libressl" &&
export   VER="3.0.0" &&
export  MJOB="-j2" &&

patch -Np1 -i ../patches/libressl-alpine/s_client-add-options-verify_.patch &&
patch -Np1 -i ../patches/libressl-alpine/starttls-ldap.patch &&

autoreconf -vif &&

case $(uname -m) in
 x86_64)  export EXTRACONFIG=""
          export TRUPLE="x86_64-linux-musl"
         ;;
 i686)    export EXTRACONFIG="--disable-hardening"
          export TRUPLE="i686-linux-musl"
         ;;
 armv7l)  export TRUPLE="armv7l-linux-musleabihf"
         ;;
 armv6l)  export TRUPLE="armv6l-linux-musleabihf"
         ;;
 aarch64) export TRUPLE="aarch64-linux-musleabihf"
         ;;
esac &&

CFLAGS="-L/usr/lib $CFLAGS" \
./configure \
           --build=$TRUPLE \
           --host=$TRUPLE \
           --prefix=/usr \
           --sysconfdir=/etc \
           --mandir=/usr/share/man \
           --localstatedir=/var $EXTRACONFIG

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&
unset EXTRACONFIG TRUPLE&&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

