#! /bin/bash

# Python
# Source:  https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="python3" &&
export   VER="3.9.1"  &&
export  MJOB="-j2"    &&

patch -Np0 -i ../patches/python3-void/musl-find_library.patch &&
patch -Np0 -i ../patches/python3-void/tweak-MULTIARCH-for-powerpc-linux-musl.patch &&

rm -r Modules/expat                    &&
rm -r Modules/_ctypes/{darwin,libffi}* &&

./configure --prefix=/usr       \
            --enable-shared     \
            --with-system-expat \
            --with-system-ffi   \
            --with-ensurepip=yes \
            --enable-ipv6 \
            --with-threads \
            --enable-loadable-sqlite-extensions \
            --with-computed-gotos $BTRUPLE &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&
chmod -v 755 ${BUILD}/usr/lib/libpython3.9.so &&
chmod -v 755 ${BUILD}/usr/lib/libpython3.so   &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

