#! /bin/bash

# Ninja
# Source:  https://github.com/ninja-build/ninja/archive/v1.10.0/ninja-1.10.0.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="ninja"  &&
export   VER="1.10.0" &&
export  MJOB="-j2"    &&

# If desired, add the capability to use the
# environment variable NINJAJOBS
sed -i '/int Guess/a \
  int   j = 0;\
  char* jobs = getenv( "NINJAJOBS" );\
  if ( jobs != NULL ) j = atoi( jobs );\
  if ( j > 0 ) return j;\
' src/ninja.cc &&

read -p "Compile?" && python3 configure.py --bootstrap &&

mkdir -pv ${BUILD}/usr/bin &&
mkdir -pv ${BUILD}/usr/share/bash-completion/completions/ninja &&
mkdir -pv ${BUILD}/usr/share/zsh/site-functions/_ninja &&
install -vm755 ninja ${BUILD}/usr/bin/ &&
install -vDm644 misc/bash-completion ${BUILD}/usr/share/bash-completion/completions/ninja
install -vDm644 misc/zsh-completion  ${BUILD}/usr/share/zsh/site-functions/_ninja

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

