#! /bin/bash

# Meson
# Source: https://github.com/mesonbuild/meson/releases/download/0.55.1/meson-0.55.1.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="meson"  &&
export   VER="0.55.1" &&
export  MJOB="-j2"    &&

read -p "Compile?" && python3 setup.py build &&

python3 setup.py install --root=dest &&
cp -rv dest/* ${BUILD}/ &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

