#! /bin/bash

# Procps-ng
# Source: https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-3.3.16.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="procps-ng" &&
export   VER="3.3.16"    &&
export  MJOB="-j2" &&

autoreconf -fiv &&
patch -Np1 -i ../patches/procps-adelie/use-utmpx.patch &&

LIBS="$LIBS -lutmps -lskarnet"   \
ac_cv_func_malloc_0_nonnull=yes  \
ac_cv_func_realloc_0_nonnull=yes \
./configure --prefix=/usr                            \
            --exec-prefix=                           \
            --libdir=/usr/lib                        \
            --docdir=/usr/share/doc/procps-ng-${VER} \
            --disable-static                         \
            --disable-kill                           \
            --enable-watch8bit                       \
            --without-systemd \
            --disable-modern-top $BTRUPLE &&
read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&
mkdir -pv ${BUILD}/lib        &&
mv -v ${BUILD}/usr/lib/libprocps.so.* ${BUILD}/lib
ln -sfv ../../lib/libprocps.so.8.0.2 ${BUILD}/usr/lib/libprocps.so &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

