#! /bin/bash

# Findutils
# Source: http://ftp.gnu.org/gnu/findutils/findutils-4.7.0.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="findutils" &&
export   VER="4.7.0"     &&
export  MJOB="-j2"       &&

./configure --prefix=/usr \
            --localstatedir=/var/lib/locate ${BTRUPLE} &&
read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&
mkdir -pv ${BUILD}/bin &&
mv -v ${BUILD}/usr/bin/find ${BUILD}/bin &&
sed -i 's|find:=${BINDIR}|find:=/bin|' ${BUILD}/usr/bin/updatedb &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

