#! /bin/bash

# Gawk
# Source: http://ftp.gnu.org/gnu/gawk/gawk-5.1.0.tar.xz 
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="gawk"      &&
export   VER="5.1.0"     &&
export  MJOB="-j2"       &&

sed -i 's/extras//' Makefile.in      &&
./configure --prefix=/usr ${BTRUPLE} &&
read -p "Compile?" && make ${MJOB}   &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

