#! /bin/bash

# Grub
# Source: https://ftp.gnu.org/gnu/grub/grub-2.04.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="grub" &&
export   VER="2.04" &&
export  MJOB="-j2"  &&
export  VRTN="uefi" &&

./configure --prefix=/usr          \
            --target=x86_64        \
            --with-platform=efi    \
            --sbindir=/sbin        \
            --sysconfdir=/etc      \
            --disable-werror &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}_${VRTN}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}_${VRTN}-$PSUFFIX

