#! /bin/bash

# Less
# Source: http://www.greenwoodsoftware.com/less/less-563.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="less"      &&
export   VER="563"       &&
export  MJOB="-j2"       &&

./configure --prefix=/usr --sysconfdir=/etc ${BTRUPLE} &&
read -p "Compile?" && make ${MJOB}   &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

