#! /bin/bash

# Texinfo
# Source: http://ftp.gnu.org/gnu/texinfo/texinfo-6.7.tar.xz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="texinfo" &&
export   VER="6.7" &&
export  MJOB="-j2" &&

./configure --prefix=/usr \
            --disable-static ${BTRUPLE} &&
read -p "Compile?" && make ${MJOB}      &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

