#! /bin/bash

# S6
# Source: https://www.skarnet.org/software/s6/s6-2.9.2.0.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="s6"      &&
export   VER="2.9.2.0" &&
export  MJOB="-j2"     &&

./configure  --prefix=/usr \
             --bindir=/bin \
             --with-lib=/usr/lib/skalibs \
             --with-lib=/usr/lib/libexec \
             --with-lib=/usr/lib/execline \
             --with-dynlib=/usr/lib \
             --enable-shared ${BTRUPLE} &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

