#! /bin/bash

# Execline
# Source: https://skarnet.org/software/execline/execline-2.6.1.1.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="execline" &&
export   VER="2.6.1.1"  &&
export  MJOB="-j2"      &&

./configure --enable-shared       \
            --enable-static       \
            --enable-allstatic    \
            --enable-static-libc  \
	    --libdir=/usr/lib     \
	    --with-dynlib=/lib    \
            --enable-pedantic-posix ${BTRUPLE} &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

