#! /bin/bash

# S6-Linux-Utils 
# Source: https://www.skarnet.org/software/s6-linux-utils/s6-linux-utils-2.5.1.3.tar.gz
#
# $BUILD = Directory to temporarily install
# $PKGS  = Directory to store built packages
# $DESCS = Directory of package descriptions
#
# $BTRUPLE = Architecture Specifier i.e. i686-linux-musl
# $PSUFFIX = Architecture and Distro of package
export PNAME="s6-linux-utils" &&
export   VER="2.5.1.3"        &&
export  MJOB="-j2"            &&

./configure --disable-allstatic \
            --prefix=/usr       \
	    --with=dynlib=/lib ${BTRUPLE} &&

read -p "Compile?" && make ${MJOB} &&

make DESTDIR=${BUILD} install &&

cd ${BUILD} && mkdir -v ${BUILD}/install          &&
cp -v $DESCS/${PNAME} ${BUILD}/install/slack-desc &&
makepkg -l y -c n $PKGS/${PNAME}-${VER}-$PSUFFIX  &&
rm -rf ${BUILD}/* && installpkg $PKGS/${PNAME}-${VER}-$PSUFFIX

