#! /bin/bash

# Shadow 
# v7.00
# Run in chroot
#
# syntax *.build <package.tar.xz> <number of make jobs>
# $BUILD  = Directory to temporarily install
# $PKGS   = Directory to store built packages
# $MJ     = number of make jobs like -j3 for 3
# $SUFFIX = package file extenstion, i.e. i686-mlfs.txz 
# $DESCS  = Directory of package descriptions

# Load pkg build system configuration                          ##
source /sources/scripts/0-build.config                         &&
# Extract package info                                         ##
export PACKAGE=$(echo "$1" | cut -d "." -f -3 )                &&
#export PACKAGENAME="packagename  "                            &&
export PACKAGENAME=$(echo "$1" | cut -d "." -f -3 | cut -d "-" -f -1 ) &&
export PVER=$(echo "$1" | cut -d "." -f -3 | cut -d "-" -f 2 ) &&
cd $PACKAGE                                                    &&
#################################################################

sed -i 's/groups$(EXEEXT) //' src/Makefile.in                      &&
find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;  &&
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;  &&
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;  &&
sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
	       -e 's@/var/spool/mail@/var/mail@' etc/login.defs    &&
sed -i 's/1000/999/' etc/useradd                                   &&
touch /usr/bin/passwd                                              &&
./configure --sysconfdir=/etc --with-group-name-max-length=32      &&
make $MJ                      &&
make DESTDIR=${BUILD} install &&
mkdir -pv ${BUILD}/bin        &&

#strip
find ${BUILD} | xargs file | grep -e "executable" -e "shared object" \
	  | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null &&

cd ${BUILD} && mkdir -v ${BUILD}/install   &&
cp -v ${DESCS}/${PACKAGENAME} install/slack-desc  &&
mv -v usr/bin/passwd bin                &&
sed -i 's/yes/no/' etc/default/useradd &&
makepkg -l y -c n ${PKGS}/${PACKAGENAME}-${PVER}-${SUFFIX}  &&
echo 'echo "Enabling shadow passowrds.."' >> install/doinst.sh &&
echo "pwconv && grpconv" >> install/doinst.sh                  &&
echo 'echo "Set system root passowrd:"' >> install/doinst.sh   &&
echo "passwd root" >> install/doinst.sh                        &&
makepkg -l y -c n ${PKGS}/${PACKAGENAME}-${PVER}-${SUFFIX}  &&
installpkg        ${PKGS}/${PACKAGENAME}-${PVER}-${SUFFIX}  &&
cd - && cd ..                                                   &&
printf  "${BLUEC}*** Removing unpacked package source.${NORMALC}\n" && 
rm -rf $PACKAGE &&
printf "${GREENC}*** Cleaning stage.${NORMALC}${NORMALC}\n"         && 
rm -rf ${BUILD}/*

