#! /bin/bash

# Ninja 
# v7.00
# Run in chroot
#
# syntax *.build <package.tar.xz> <number of make jobs>
# $BUILD  = Directory to temporarily install
# $PKGS   = Directory to store built packages
# $MJ     = number of make jobs like -j3 for 3
# $SUFFIX = package file extenstion, i.e. i686-mlfs.txz 
# $DESCS  = Directory of package descriptions

# Load pkg build system configuration                          ##
source /sources/scripts/0-build.config                         &&
# Extract package info                                         ##
export PACKAGE=$(echo "$1" | cut -d "." -f -3 )                &&
export PACKAGENAME=$(echo "$1" | cut -d "." -f -3 | cut -d "-" -f -1 ) &&
export PVER=$(echo "$1" | cut -d "." -f -3 | cut -d "-" -f 2 ) &&
cd $PACKAGE                                                    &&
#################################################################
sed -i '/int Guess/a                    \
  int   j = 0;                          \
  char* jobs = getenv( "NINJAJOBS" );   \
  if ( jobs != NULL ) j = atoi( jobs ); \
  if ( j > 0 ) return j;                \
' src/ninja.cc &&
python3 configure.py --bootstrap       &&
mkdir -pv ${BUILD}/usr/share/bash-completion/completions/ninja &&
mkdir -pv ${BUILD}/usr/share/zsh/site-functions/_ninja         &&
mkdir -pv ${BUILD}/usr/bin                                     &&
install -vm755 ninja ${BUILD}/usr/bin/                         &&
install -vDm644 misc/bash-completion ${BUILD}/usr/share/bash-completion/completions/ninja &&
install -vDm644 misc/zsh-completion  ${BUILD}/usr/share/zsh/site-functions/_ninja         &&
#strip
find ${BUILD} | xargs file | grep -e "executable" -e "shared object" \
	  | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null &&

cd ${BUILD} && mkdir -v ${BUILD}/install   &&
cp -v ${DESCS}/${PACKAGENAME} install/slack-desc  &&
makepkg -l y -c n ${PKGS}/${PACKAGENAME}-${PVER}-${SUFFIX}  &&
installpkg        ${PKGS}/${PACKAGENAME}-${PVER}-${SUFFIX}  &&
cd - && cd ..                                                   &&
printf  "${BLUEC}*** Removing unpacked package source.${NORMALC}\n" && 
rm -rf $PACKAGE &&
printf "${GREENC}*** Cleaning stage.${NORMALC}${NORMALC}\n"         && 
rm -rf ${BUILD}/*

