#! /bin/bash

# Man-DB 
# v7.00
# Run in chroot
#
# syntax *.build <package.tar.xz> <number of make jobs>
# $BUILD  = Directory to temporarily install
# $PKGS   = Directory to store built packages
# $MJ     = number of make jobs like -j3 for 3
# $SUFFIX = package file extenstion, i.e. i686-mlfs.txz 
# $DESCS  = Directory of package descriptions

# Load pkg build system configuration                          ##
source /sources/scripts/0-build.config                         &&
# Extract package info                                         ##
export PACKAGE=$(echo "$1" | cut -d "." -f -3 )                &&
export PACKAGENAME=$(echo "$1" | cut -d "." -f -3 | cut -d "-" -f -2 ) &&
export PVER=$(echo "$1" | cut -d "." -f -3 | cut -d "-" -f 3 ) &&
cd $PACKAGE                                                    &&
#################################################################
patch -Np0 -i ../patches/man-db-void/guard-glibc-iconv-ext.patch        &&
patch -Np0 -i ../patches/man-db-void/add-missing-stdlib_h-include.patch &&
export CFLAGS+=" -I/usr/include/gettext"  &&
export LDFLAGS+=" -lintl"                 &&
./configure --prefix=/usr                        \
            --docdir=/usr/share/doc/man-db-${PVER} \
            --sysconfdir=/etc                    \
            --disable-setuid                     \
            --enable-cache-owner=bin             \
            --with-browser=/usr/bin/lynx         \
            --with-vgrind=/usr/bin/vgrind        \
            --with-grap=/usr/bin/grap            \
            --with-systemdtmpfilesdir=           \
            --with-systemdsystemunitdir=         \
            --with-pager=less                    \
            --disable-rpath                      \
            --enable-threads=posix               \
            --without-included-regex             \
            --enable-automatic-create     &&
make $MJ && make DESTDIR=${BUILD} install &&
unset CFLAGS LDFLAGS &&
#strip
find ${BUILD} | xargs file | grep -e "executable" -e "shared object" \
	  | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null &&

cd ${BUILD} && mkdir -v ${BUILD}/install   &&
cp -v ${DESCS}/${PACKAGENAME} install/slack-desc  &&
makepkg -l y -c n ${PKGS}/${PACKAGENAME}-${PVER}-${SUFFIX}  &&
installpkg        ${PKGS}/${PACKAGENAME}-${PVER}-${SUFFIX}  &&
cd - && cd ..                                                   &&
printf  "${BLUEC}*** Removing unpacked package source.${NORMALC}\n" && 
rm -rf $PACKAGE &&
printf "${GREENC}*** Cleaning stage.${NORMALC}${NORMALC}\n"         && 
rm -rf ${BUILD}/*

