#! /bin/bash

# S6-linux-init 
# v7.00
# Run in chroot
#
# syntax *.build <package.tar.xz> <number of make jobs>
# $BUILD  = Directory to temporarily install
# $PKGS   = Directory to store built packages
# $MJ     = number of make jobs like -j3 for 3
# $SUFFIX = package file extenstion, i.e. i686-mlfs.txz 
# $DESCS  = Directory of package descriptions

# Load pkg build system configuration                          ##
source /sources/scripts/0-build.config                         &&
# Extract package info                                         ##
export PACKAGE=$(echo "$1" | cut -d "." -f -4 )                &&
export PACKAGENAME=$(echo "$1" | cut -d "." -f -4 | cut -d "-" -f -3 ) &&
export PVER=$(echo "$1" | cut -d "." -f -4 | cut -d "-" -f 4 ) &&
cd $PACKAGE                                                    &&
#################################################################
./configure --prefix=/usr \
            --with-lib=/usr/lib/skalibs \
            --with-lib=/usr/lib/libexec \
            --with-lib=/usr/lib/execline \
            --with-lib=/usr/lib/s6 \
            --with-dynlib=/usr/lib \
            --enabled-share &&
make $MJ && make DESTDIR=${BUILD} install &&
#strip
find ${BUILD} | xargs file | grep -e "executable" -e "shared object" \
	  | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null &&

cd ${BUILD} && mkdir -v ${BUILD}/install   &&
cp -v ${DESCS}/${PACKAGENAME} install/slack-desc  &&
makepkg -l y -c n ${PKGS}/${PACKAGENAME}-${PVER}-${SUFFIX}  &&
installpkg        ${PKGS}/${PACKAGENAME}-${PVER}-${SUFFIX}  &&
cd - && cd ..                                                   &&
printf  "${BLUEC}*** Removing unpacked package source.${NORMALC}\n" && 
rm -rf $PACKAGE &&
printf "${GREENC}*** Cleaning stage.${NORMALC}${NORMALC}\n"         && 
rm -rf ${BUILD}/*

